### ISSUE TITLE
bug: unable to do getproducts

### ISSUE THREAD

**Issue by Chromicle** [RayOkaah/woocommerce#11]
while I am trying to fetch products
```
E/flutter (15453): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'String' is not a subtype of type 'int'
E/flutter (15453): #0      new WooProduct.fromJson (package:woocommerce/models/products.dart:172:20)
E/flutter (15453): #1      WooCommerce.getProducts (package:woocommerce/woocommerce.dart:461:29)
```

can anyone get me fix

**Comment by sharecube** [comment]
you need to use String as product category, this would work

**Comment by sharecube** [comment]
> while I am trying to fetch products
> 
> ```
> E/flutter (15453): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'String' is not a subtype of type 'int'
> E/flutter (15453): #0      new WooProduct.fromJson (package:woocommerce/models/products.dart:172:20)
> E/flutter (15453): #1      WooCommerce.getProducts (package:woocommerce/woocommerce.dart:461:29)
> ```
> 
> can anyone get me fix

you need to use String as product category, this would work

**Comment by Chromicle** [comment]
it is actually a string, 

I am still facing this issue for JWT auth also

**Comment by RayOkaah** [comment]
I cant wrap my head around what is the string value throwing that error?

**Comment by Chromicle** [comment]
you can use this https://github.com/yhhCh405/yhhFlutterWoocommerce/tree/master/ plugin 

it works fine for me
