### ISSUE TITLE
WooCommerceError message

### ISSUE THREAD

**Issue by ChristianAdrian** [RayOkaah/woocommerce#36]
`try {
      result = await woocommerce.createCustomer(sut);
      Get.back();
    } on WooCommerceError catch (e) {
      Get.back();
      mess = e.message;
      Get.defaultDialog(
          barrierDismissible: false,
          title: 'Oops!',
          textCancel: 'close',
          onCancel: () {},
          middleText: e.message);
    }`

I have been trying to display the error message whenever a user creates an account but this is not working what am I doing wrong

**Comment by Michele-x98** [comment]
You need to remove the Exception throw on _handleErro(), you only need to throw a WooCommerceError() and not a Exception(WooCommerceError()...);
