### ISSUE TITLE
authenticateViaJWT get null

### ISSUE THREAD

**Issue by bonzinho** [RayOkaah/woocommerce#37]
When trying to authenticate by JWT, the authenticateViaJWT method returns null.

I made the debug and the authentication is being done and returns the status 200 and all the info, but in the method

WooJWTResponse authResponse =          
      _authToken = authResponse.token;

is passed null.

before the response has all the info

**Comment by bonzinho** [comment]
Sorry, i have installed wrong plugin jwt.

**Comment by GitGud31** [comment]
@bonzinho  which plugin jwt worked for you ?
